### ISSUE TITLE
 dynamic RowHeader and ColumnHeader

### ISSUE THREAD

**Issue by alasari** [evrencoskun/TableViewSampleApp#2]
how to set the cell when the rowHeader and ColumnHeader is dynamic by db.value(SQLiteDB).
 I just confused how to set the contents of the cell according to rowhead and columhead

`

            for (int x = 0; x < getColumnHeaderList().size(); x++) {
                NilaiAdapter adapter = new NilaiAdapter(getContext());
                List<String> Celldb = adapter.getallcell();
                String strText = Celldb.get(x);
                Cell cell = new Cell(strID, strText);
                cellList.add(cell);
            }

`

**Comment by evrencoskun** [comment]
Hi alasari,

I didn't understand what you mean actually. 

You want to show your SQLite datas on a TableView. Am I right ? 

If I am, there is no any direct connection by SQLiteDB to TableView. You should build the your own. And a TableView, wants some lists that are represent column headers, row headers and cell items. 

Please look sample apps to get rid of your confision.  


> I just confused how to set the contents of the cell according to rowhead and columhead

If you want to change spesific content on TableView, for that, there are also some helper methods on your TableViewAdapter.

These are; 

- `addRow(int yPosition, RH rowHeaderItem, List<C>cellItems)`
- `addRowRange(int yPositionStart, int itemCount, List<RH> rowHeaderItem, List<List<C>> cellItems)`
- `removeRow(int yPosition)`
- `removeRowRange(int yPositionStart, int itemCount)`
- `changeRowHeaderItem(int yPosition, RH rowHeaderModel)`
- `changeRowHeaderItemRange(int yPositionStart, int itemCount, List<RH>rowHeaderModelList)`
- `changeCellItem(int xPosition, int yPosition, C cellModel)`
- `changeColumnHeader(int xPosition, CH columnHeaderModel)`
- `changeColumnHeaderRange(int xPositionStart, int itemCount, List<CH>columnHeaderModelList)`
