### ISSUE TITLE
How to update table row...?

### ISSUE THREAD

**Issue by alasari** [evrencoskun/TableViewSampleApp#4]
Hi @evrencoskun , I would like to ask again 😀 , how to update the one row of the table `..?

**Comment by evrencoskun** [comment]
Hi @alasari 
If you want to change specific content on TableView, for that, there are also some helper methods on your TableViewAdapter.

These are;

- `getColumnHeaderItem(int columnPosition)`
- `getRowHeaderItem(int rowPosition)`
- `getCellItem(int columnPosition, int rowPosition)`
- `getCellRowItems(int rowPosition)`
- `getCellColumnItems(int columnPosition)`
- `removeRow(int rowPosition)`
- `removeRowRange(int rowPositionStart, int itemCount)` 
- `removeColumn(int columnPosition)`
- `addRow(int rowPosition, RH rowHeaderItem, List<C> cellItems)`
- `addRowRange(int rowPositionStart, List<RH> rowHeaderItem, List<List<C>> cellItems)`
- `addColumn(int columnPosition, CH columnHeaderItem, List<C> cellItems)`
- `changeRowHeaderItem(int rowPosition, RH rowHeaderModel)`
- `changeRowHeaderItemRange(int rowPositionStart, List<RH> rowHeaderModelList)`
- `changeCellItem(int columnPosition, int rowPosition, C cellModel)`
- `changeColumnHeader(int columnPosition, CH columnHeaderModel)`
- `changeColumnHeaderRange(int columnPositionStart, List<CH> columnHeaderModelList)`

**Comment by alasari** [comment]
Hi @evrencoskun, thanks for your response, this library is awesome 😀

**Comment by evrencoskun** [comment]
Thank you @alasari :)
